version: '3.0'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      # read-only mount the aws config and credentials from the hostsystem
      - ~/.aws:/home/devuser/.aws:ro
    ports:
      - "3000"
      - "8921:5000"
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    user: devuser